spring.application.name=monitoring-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=monitoring-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

monitoring.thresholds.temperature=35.0
monitoring.thresholds.humidity=50.0
monitoring.kafka.topics.temperature=temperature.readings
monitoring.kafka.topics.humidity=humidity.readings

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

logging.level.root=INFO
logging.level.com.warehouse.monitoring=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.reactor.kafka=DEBUG
logging.level.ALARM=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

server.port=8082

